/**
 * Sub-lesson paths where “Mark as done for me” and daily-test pools apply.
 * Keep in sync with navigation / dashboard lesson lists.
 */
export const GRAMMAR_LESSON_PATHS = [
  '/grammar/grammatical-gender',
  '/grammar/cases',
  '/grammar/declensions',
  '/grammar/present-tense-active',
  '/grammar/adjectives',
  '/grammar/relative-pronoun',
  '/grammar/adjectives-adverbial-force',
  '/grammar/imperative',
  '/grammar/ne-questions',
  '/grammar/demonstrative-pronouns-i',
  '/grammar/demonstrative-pronouns-ii',
  '/grammar/demonstrative-pronouns-iii',
  '/grammar/demonstrative-pronouns-iv',
] as const;

export const VOCABULARY_LESSON_PATHS = [
  '/vocabulary/animals/common',
  '/vocabulary/animals/wild',
  '/vocabulary/animals/birds',
  '/vocabulary/animals/sea',
  '/vocabulary/animals/small',
  '/vocabulary/food/basic',
  '/vocabulary/food/fruits',
  '/vocabulary/food/vegetables',
  '/vocabulary/food/meat',
  '/vocabulary/food/drinks',
  '/vocabulary/body-parts/basic',
  '/vocabulary/body-parts/face',
  '/vocabulary/body-parts/internal',
  '/vocabulary/rooms/living-sleeping',
  '/vocabulary/rooms/eating-cooking',
  '/vocabulary/rooms/general',
  '/vocabulary/rooms/washing',
  '/vocabulary/rooms/study-work',
  '/vocabulary/rooms/outdoor',
  '/vocabulary/landscape/land',
  '/vocabulary/landscape/mountains',
  '/vocabulary/landscape/water',
  '/vocabulary/landscape/plants',
  '/vocabulary/landscape/sky-weather',
  '/vocabulary/landscape/elements',
  '/vocabulary/marketplace/places-people',
  '/vocabulary/marketplace/money-trade',
  '/vocabulary/marketplace/carrying',
  '/vocabulary/marketplace/equipment',
  '/vocabulary/family/immediate-family',
  '/vocabulary/family/extended-family',
  '/vocabulary/family/other-relations',
  '/vocabulary/occupations/general',
  '/vocabulary/occupations/military-government',
  '/vocabulary/occupations/education',
  '/vocabulary/occupations/crafts-trades',
  '/vocabulary/occupations/arts-entertainment',
  '/vocabulary/core-actions/daily-actions',
  '/vocabulary/core-actions/senses-perception',
  '/vocabulary/core-actions/communication',
  '/vocabulary/core-actions/thinking-knowing',
  '/vocabulary/core-actions/emotion-desire',
  '/vocabulary/core-actions/irregular-verbs',
  '/vocabulary/environment-interaction/home-actions',
  '/vocabulary/environment-interaction/marketplace-money',
  '/vocabulary/environment-interaction/military-government',
  '/vocabulary/environment-interaction/nature-movement',
  '/vocabulary/environment-interaction/weather-phenomena',
  '/vocabulary/society-relationships/family-relationships',
  '/vocabulary/society-relationships/learning-teaching',
  '/vocabulary/society-relationships/travel-exploration',
  '/vocabulary/society-relationships/religion-ritual',
  '/vocabulary/society-relationships/law-society',
  '/vocabulary/irregular-verbs/essential',
  '/vocabulary/irregular-verbs/common-irregulars',
  '/vocabulary/irregular-verbs/compound',
] as const;

export const TRACKED_LESSON_PATHS: readonly string[] = [
  ...GRAMMAR_LESSON_PATHS,
  ...VOCABULARY_LESSON_PATHS,
];

export const DAILY_TEST_MAX_QUESTIONS = 30;

export const DAILY_TEST_QUIZ_PATH = '/dashboard/daily/test';
