import type { QuizQuestion } from '@/lib/buildVocabularyQuestionBank';

export const presentTenseActiveQuiz: QuizQuestion[] = [
  { question: 'The Latin present tense is used for:', options: ['Only past actions', 'Only future actions', 'Actions now, regularly, and general truths', 'Only completed actions'], correct: 2 },
  { question: 'Latin verbs show the subject by:', options: ['Word order', 'Endings', 'Prefixes', 'Capital letters'], correct: 1 },
  { question: 'What determines which ending is used?', options: ['The noun gender', 'The verb stem and conjugation', 'The sentence length', 'The object'], correct: 1 },
  { question: 'Which is TRUE?', options: ['Endings are completely different for every verb', 'Endings are mostly consistent across verbs', 'Latin has no verb endings', 'Only singular has endings'], correct: 1 },
  { question: 'What is the ending for "I"?', options: ['-s', '-ō', '-t', '-mus'], correct: 1 },
  { question: 'What is the ending for "you" (singular)?', options: ['-tis', '-nt', '-s', '-mus'], correct: 2 },
  { question: 'What is the ending for "he/she/it"?', options: ['-ō', '-t', '-mus', '-nt'], correct: 1 },
  { question: 'What is the ending for "we"?', options: ['-mus', '-tis', '-nt', '-s'], correct: 0 },
  { question: 'What is the ending for "you" (plural)?', options: ['-mus', '-tis', '-nt', '-ō'], correct: 1 },
  { question: 'What is the ending for "they"?', options: ['-ō', '-s', '-t', '-nt'], correct: 3 },
  { question: 'What does amāre mean?', options: ['To see', 'To love', 'To read', 'To hear'], correct: 1 },
  { question: 'What is "I love"?', options: ['amās', 'amat', 'amō', 'amant'], correct: 2 },
  { question: 'What is "we love"?', options: ['amātis', 'amāmus', 'amant', 'amās'], correct: 1 },
  { question: 'What is "they love"?', options: ['amat', 'amō', 'amant', 'amās'], correct: 2 },
  { question: 'Which form is "you (singular) love"?', options: ['amō', 'amās', 'amat', 'amāmus'], correct: 1 },
  { question: 'What does vidēre mean?', options: ['To love', 'To hear', 'To see', 'To read'], correct: 2 },
  { question: 'What is "I see"?', options: ['vidēs', 'videō', 'videt', 'vident'], correct: 1 },
  { question: 'What is "they see"?', options: ['vidēmus', 'vidētis', 'vident', 'videō'], correct: 2 },
  { question: 'What is "you (plural) see"?', options: ['vidēs', 'vidētis', 'videt', 'vident'], correct: 1 },
  { question: 'What does legere mean?', options: ['To read', 'To hear', 'To love', 'To see'], correct: 0 },
  { question: 'What is "I read"?', options: ['legis', 'legit', 'legō', 'legunt'], correct: 2 },
  { question: 'What is "they read"?', options: ['legitis', 'legimus', 'legunt', 'legit'], correct: 2 },
  { question: 'What is "we read"?', options: ['legimus', 'legitis', 'legunt', 'legis'], correct: 0 },
  { question: 'What does audīre mean?', options: ['To see', 'To hear', 'To love', 'To read'], correct: 1 },
  { question: 'What is "I hear"?', options: ['audīs', 'audit', 'audiō', 'audiunt'], correct: 2 },
  { question: 'What is "they hear"?', options: ['audit', 'audiunt', 'audīmus', 'audītis'], correct: 1 },
  { question: 'What is "you (plural) hear"?', options: ['audīs', 'audītis', 'audiō', 'audiunt'], correct: 1 },
  { question: 'Which ending always indicates plural?', options: ['-ō', '-s', '-mus / -tis / -nt', '-t'], correct: 2 },
  { question: 'Which ending always indicates singular?', options: ['-mus', '-tis', '-nt', '-ō / -s / -t'], correct: 3 },
  { question: 'Which pair matches correctly?', options: ['-ō -> they', '-nt -> they', '-s -> we', '-mus -> he'], correct: 1 },
  { question: 'What does amant mean?', options: ['I love', 'You love', 'He loves', 'They love'], correct: 3 },
  { question: 'What does vides mean?', options: ['I see', 'You see', 'He sees', 'They see'], correct: 1 },
  { question: 'What does legimus mean?', options: ['I read', 'You read', 'We read', 'They read'], correct: 2 },
  { question: 'What does audiunt mean?', options: ['I hear', 'You hear', 'They hear', 'We hear'], correct: 2 },
  { question: 'Why do not you always need pronouns in Latin?', options: ['They do not exist', 'The verb ending shows the subject', 'Latin avoids subjects', 'Only nouns are used'], correct: 1 },
  { question: 'Which is TRUE about learning endings?', options: ['Must memorize immediately', 'Cannot be learned', 'Will stick with practice', 'Are optional'], correct: 2 },
];
