import type { VocabularyFlashcard } from '@/components/VocabularyFlashcards';

/** All Animalia sub-lesson cards (one deck). */
export const ANIMALS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'Canis', english: 'Dog', icon: '/flashcard-icons/animals/canis.svg' },
  { latin: 'Fēlīs', english: 'Cat', icon: '/flashcard-icons/animals/feles.svg' },
  { latin: 'Equus', english: 'Horse', icon: '/flashcard-icons/animals/equus.svg' },
  { latin: 'Vacca', english: 'Cow', icon: '/flashcard-icons/animals/vacca.svg' },
  { latin: 'Porcus', english: 'Pig', icon: '/flashcard-icons/animals/porcus.svg' },
  { latin: 'Ovis', english: 'Sheep', icon: '/flashcard-icons/animals/ovis.svg' },
  { latin: 'Capra', english: 'Goat', icon: '/flashcard-icons/animals/capra.svg' },
  { latin: 'Asīnus', english: 'Donkey', icon: '/flashcard-icons/animals/asinus.svg' },
  { latin: 'Lēo', english: 'Lion', icon: '/flashcard-icons/animals/leo.svg' },
  { latin: 'Tigris', english: 'Tiger', icon: '/flashcard-icons/animals/tigris.svg' },
  { latin: 'Ursus', english: 'Bear', icon: '/flashcard-icons/animals/ursus.svg' },
  { latin: 'Lupus', english: 'Wolf', icon: '/flashcard-icons/animals/lupus.svg' },
  { latin: 'Vulpes', english: 'Fox', icon: '/flashcard-icons/animals/vulpes.svg' },
  { latin: 'Cervus', english: 'Deer', icon: '/flashcard-icons/animals/cervus.svg' },
  { latin: 'Ēlēphāntus', english: 'Elephant', icon: '/flashcard-icons/animals/elephantus.svg' },
  { latin: 'Āvis', english: 'Bird', icon: '/flashcard-icons/animals/avis.svg' },
  { latin: 'Aquila', english: 'Eagle', icon: '/flashcard-icons/animals/aquila.svg' },
  { latin: 'Columba', english: 'Dove / pigeon', icon: '/flashcard-icons/animals/columba.svg' },
  { latin: 'Corvus', english: 'Crow', icon: '/flashcard-icons/animals/corvus.svg' },
  { latin: 'Passer', english: 'Sparrow', icon: '/flashcard-icons/animals/passer.svg' },
  { latin: 'Gallina', english: 'Hen', icon: '/flashcard-icons/animals/gallina.svg' },
  { latin: 'Gallus', english: 'Rooster', icon: '/flashcard-icons/animals/gallus.svg' },
  { latin: 'Piscis', english: 'Fish', icon: '/flashcard-icons/animals/piscis.svg' },
  { latin: 'Delphīnus', english: 'Dolphin', icon: '/flashcard-icons/animals/delphinus.svg' },
  { latin: 'Cētus', english: 'Whale', icon: '/flashcard-icons/animals/cetus.svg' },
  { latin: 'Canis mārīnus', english: 'Shark', icon: '/flashcard-icons/animals/canis-marinus.svg' },
  { latin: 'Mūs', english: 'Mouse', icon: '/flashcard-icons/animals/mus.svg' },
  { latin: 'Rāna', english: 'Frog', icon: '/flashcard-icons/animals/rana.svg' },
  { latin: 'Serpēns', english: 'Snake', icon: '/flashcard-icons/animals/serpens.svg' },
  { latin: 'Apis', english: 'Bee', icon: '/flashcard-icons/animals/apis.svg' },
  { latin: 'Formīca', english: 'Ant', icon: '/flashcard-icons/animals/formica.svg' },
];

/** All Cibus sub-lesson cards. */
export const FOOD_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'pānis', english: 'Bread', icon: '/flashcard-icons/food/panis.svg' },
  { latin: 'cāseus', english: 'Cheese', icon: '/flashcard-icons/food/caseus.svg' },
  { latin: 'ōvum', english: 'Egg', icon: '/flashcard-icons/food/ovum.svg' },
  { latin: 'cibus', english: 'Food', icon: '/flashcard-icons/food/cibus.svg' },
  { latin: 'cēna', english: 'Dinner / meal', icon: '/flashcard-icons/food/cena.svg' },
  { latin: 'mālum', english: 'Apple', icon: '/flashcard-icons/food/malum.svg' },
  { latin: 'pīrum', english: 'Pear', icon: '/flashcard-icons/food/pirum.svg' },
  { latin: 'ūva', english: 'Grape', icon: '/flashcard-icons/food/uva.svg' },
  { latin: 'fīcus', english: 'Fig', icon: '/flashcard-icons/food/ficus.svg' },
  { latin: 'cērāsum', english: 'Cherry', icon: '/flashcard-icons/food/cerasum.svg' },
  { latin: 'prūnum', english: 'Plum', icon: '/flashcard-icons/food/prunum.svg' },
  { latin: 'cārōta', english: 'Carrot', icon: '/flashcard-icons/food/carota.svg' },
  { latin: 'lactūca', english: 'Lettuce', icon: '/flashcard-icons/food/lactuca.svg' },
  { latin: 'cēpa', english: 'Onion', icon: '/flashcard-icons/food/cepa.svg' },
  { latin: 'āllium', english: 'Garlic', icon: '/flashcard-icons/food/allium.svg' },
  { latin: 'fungus', english: 'Mushroom', icon: '/flashcard-icons/food/fungus.svg' },
  { latin: 'cō', english: 'Meat', icon: '/flashcard-icons/food/caro.svg' },
  { latin: 'pōrcus', english: 'Pork / pig', icon: '/flashcard-icons/food/porcus-pork.svg' },
  { latin: 'bōs', english: 'Cow / beef', icon: '/flashcard-icons/food/bos.svg' },
  { latin: 'gallīna', english: 'Chicken', icon: '/flashcard-icons/food/gallina-chicken.svg' },
  { latin: 'piscis', english: 'Fish', icon: '/flashcard-icons/food/piscis-fish.svg' },
  { latin: 'aqua', english: 'Water', icon: '/flashcard-icons/food/aqua.svg' },
  { latin: 'lac', english: 'Milk', icon: '/flashcard-icons/food/lac.svg' },
  { latin: 'vīnum', english: 'Wine', icon: '/flashcard-icons/food/vinum.svg' },
  { latin: 'mēl', english: 'Honey', icon: '/flashcard-icons/food/mel.svg' },
  { latin: 'sāl', english: 'Salt', icon: '/flashcard-icons/food/sal.svg' },
];

/** All Corpus (body) sub-lesson cards. */
export const BODY_PARTS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'corpus', english: 'Body', icon: '/flashcard-icons/body-parts/corpus.svg' },
  { latin: 'cāput', english: 'Head', icon: '/flashcard-icons/body-parts/caput.svg' },
  { latin: 'collum', english: 'Neck', icon: '/flashcard-icons/body-parts/collum.svg' },
  { latin: 'umerus', english: 'Shoulder', icon: '/flashcard-icons/body-parts/umerus.svg' },
  { latin: 'brāchium', english: 'Arm', icon: '/flashcard-icons/body-parts/brachium.svg' },
  { latin: 'mānus', english: 'Hand', icon: '/flashcard-icons/body-parts/manus.svg' },
  { latin: 'digitus', english: 'Finger', icon: '/flashcard-icons/body-parts/digitus.svg' },
  { latin: 'pectus', english: 'Chest', icon: '/flashcard-icons/body-parts/pectus.svg' },
  { latin: 'venter', english: 'Belly / stomach', icon: '/flashcard-icons/body-parts/venter.svg' },
  { latin: 'tergum', english: 'Back', icon: '/flashcard-icons/body-parts/tergum.svg' },
  { latin: 'crūs', english: 'Leg', icon: '/flashcard-icons/body-parts/crus.svg' },
  { latin: 'pēs', english: 'Foot', icon: '/flashcard-icons/body-parts/pes.svg' },
  { latin: 'faciēs', english: 'Face', icon: '/flashcard-icons/body-parts/facies.svg' },
  { latin: 'frōns', english: 'Forehead', icon: '/flashcard-icons/body-parts/frons.svg' },
  { latin: 'oculus', english: 'Eye', icon: '/flashcard-icons/body-parts/oculus.svg' },
  { latin: 'cīlium', english: 'Eyelash', icon: '/flashcard-icons/body-parts/cilium.svg' },
  { latin: 'nāsus', english: 'Nose', icon: '/flashcard-icons/body-parts/nasus.svg' },
  { latin: 'aurēs', english: 'Ears', icon: '/flashcard-icons/body-parts/aures.svg' },
  { latin: 'maxilla', english: 'Jaw', icon: '/flashcard-icons/body-parts/maxilla.svg' },
  { latin: 'dēntēs', english: 'Tooth / teeth', icon: '/flashcard-icons/body-parts/dents.svg' },
  { latin: 'lingua', english: 'Tongue', icon: '/flashcard-icons/body-parts/lingua.svg' },
  { latin: 'cor', english: 'Heart', icon: '/flashcard-icons/body-parts/cor.svg' },
  { latin: 'pulmō', english: 'Lung', icon: '/flashcard-icons/body-parts/pulmo.svg' },
  { latin: 'hēpar', english: 'Liver', icon: '/flashcard-icons/body-parts/hepar.svg' },
  { latin: 'rēn', english: 'Kidney', icon: '/flashcard-icons/body-parts/ren.svg' },
];

/** All rooms sub-lesson cards. */
export const ROOMS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'cūbiculum', english: 'bedroom', icon: '/flashcard-icons/rooms/cubiculum.svg' },
  { latin: 'dormitōrium', english: 'sleeping room / dormitory', icon: '/flashcard-icons/rooms/dormitorium.svg' },
  { latin: 'lēctus', english: 'bed', icon: '/flashcard-icons/rooms/lectus.svg' },
  { latin: 'culīna', english: 'kitchen', icon: '/flashcard-icons/rooms/culina.svg' },
  { latin: 'trīclīnium', english: 'dining room (Roman style)', icon: '/flashcard-icons/rooms/triclinium.svg' },
  { latin: 'ātrium', english: 'main hall / central room', icon: '/flashcard-icons/rooms/atrium.svg' },
  { latin: 'tāblīnum', english: 'study / office (Roman house)', icon: '/flashcard-icons/rooms/tablinum.svg' },
  { latin: 'cella', english: 'small room / chamber', icon: '/flashcard-icons/rooms/cella.svg' },
  { latin: 'camēra', english: 'room / chamber', icon: '/flashcard-icons/rooms/camera.svg' },
  { latin: 'balneum', english: 'bath / bathroom', icon: '/flashcard-icons/rooms/balneum.svg' },
  { latin: 'lāvātōrium', english: 'washing room', icon: '/flashcard-icons/rooms/lavatorium.svg' },
  { latin: 'bibliothēca', english: 'library', icon: '/flashcard-icons/rooms/bibliotheca.svg' },
  { latin: 'officīna', english: 'workshop / workroom', icon: '/flashcard-icons/rooms/officina.svg' },
  { latin: 'hortus', english: 'garden', icon: '/flashcard-icons/rooms/hortus.svg' },
  { latin: 'peristȳlium', english: 'courtyard with columns', icon: '/flashcard-icons/rooms/peristylium.svg' },
];
