import type { VocabularyFlashcard } from '@/components/VocabularyFlashcards';

/** All Animalia sub-lesson cards (one deck). */
export const ANIMALS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'Canis', english: 'Dog', icon: '🐕' },
  { latin: 'Feles', english: 'Cat', icon: '🐈' },
  { latin: 'Equus', english: 'Horse', icon: '🐎' },
  { latin: 'Vacca', english: 'Cow', icon: '🐄' },
  { latin: 'Porcus', english: 'Pig', icon: '🐷' },
  { latin: 'Ovis', english: 'Sheep', icon: '🐑' },
  { latin: 'Capra', english: 'Goat', icon: '🐐' },
  { latin: 'Asinus', english: 'Donkey', icon: '🫏' },
  { latin: 'Leo', english: 'Lion', icon: '🦁' },
  { latin: 'Tigris', english: 'Tiger', icon: '🐯' },
  { latin: 'Ursus', english: 'Bear', icon: '🐻' },
  { latin: 'Lupus', english: 'Wolf', icon: '🐺' },
  { latin: 'Vulpes', english: 'Fox', icon: '🦊' },
  { latin: 'Cervus', english: 'Deer', icon: '🦌' },
  { latin: 'Elephantus', english: 'Elephant', icon: '🐘' },
  { latin: 'Avis', english: 'Bird', icon: '🐦' },
  { latin: 'Aquila', english: 'Eagle', icon: '🦅' },
  { latin: 'Columba', english: 'Dove / pigeon', icon: '🕊️' },
  { latin: 'Corvus', english: 'Crow', icon: '🐦‍⬛' },
  { latin: 'Passer', english: 'Sparrow', icon: '🐦' },
  { latin: 'Gallina', english: 'Hen', icon: '🐔' },
  { latin: 'Gallus', english: 'Rooster', icon: '🐓' },
  { latin: 'Piscis', english: 'Fish', icon: '🐟' },
  { latin: 'Delphinus', english: 'Dolphin', icon: '🐬' },
  { latin: 'Cetus', english: 'Whale', icon: '🐋' },
  { latin: 'Canis Marinus', english: 'Shark', icon: '🦈' },
  { latin: 'Mus', english: 'Mouse', icon: '🐭' },
  { latin: 'Rana', english: 'Frog', icon: '🐸' },
  { latin: 'Serpens', english: 'Snake', icon: '🐍' },
  { latin: 'Apis', english: 'Bee', icon: '🐝' },
  { latin: 'Formica', english: 'Ant', icon: '🐜' },
];

/** All Cibus sub-lesson cards. */
export const FOOD_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'panis', english: 'Bread', icon: '🍞' },
  { latin: 'caseus', english: 'Cheese', icon: '🧀' },
  { latin: 'ovum', english: 'Egg', icon: '🥚' },
  { latin: 'cibus', english: 'Food', icon: '🍱' },
  { latin: 'cena', english: 'Dinner / meal', icon: '🍽️' },
  { latin: 'malum', english: 'Apple', icon: '🍎' },
  { latin: 'pirum', english: 'Pear', icon: '🍐' },
  { latin: 'uva', english: 'Grape', icon: '🍇' },
  { latin: 'ficus', english: 'Fig', icon: '🌳' },
  { latin: 'cerasum', english: 'Cherry', icon: '🍒' },
  { latin: 'prunum', english: 'Plum', icon: '🟣' },
  { latin: 'carota', english: 'Carrot', icon: '🥕' },
  { latin: 'lactuca', english: 'Lettuce', icon: '🥬' },
  { latin: 'cepa', english: 'Onion', icon: '🧅' },
  { latin: 'allium', english: 'Garlic', icon: '🧄' },
  { latin: 'fungus', english: 'Mushroom', icon: '🍄' },
  { latin: 'caro', english: 'Meat', icon: '🥩' },
  { latin: 'porcus', english: 'Pork / pig', icon: '🐷' },
  { latin: 'bos', english: 'Cow / beef', icon: '🐄' },
  { latin: 'gallina', english: 'Chicken', icon: '🐔' },
  { latin: 'piscis', english: 'Fish', icon: '🐟' },
  { latin: 'aqua', english: 'Water', icon: '💧' },
  { latin: 'lac', english: 'Milk', icon: '🥛' },
  { latin: 'vinum', english: 'Wine', icon: '🍷' },
  { latin: 'mel', english: 'Honey', icon: '🍯' },
  { latin: 'sal', english: 'Salt', icon: '🧂' },
];

/** All Corpus (body) sub-lesson cards. */
export const BODY_PARTS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'corpus', english: 'Body', icon: '🧍' },
  { latin: 'caput', english: 'Head', icon: '👤' },
  { latin: 'collum', english: 'Neck', icon: '🧣' },
  { latin: 'umerus', english: 'Shoulder', icon: '👔' },
  { latin: 'brachium', english: 'Arm', icon: '💪' },
  { latin: 'manus', english: 'Hand', icon: '🖐️' },
  { latin: 'digitus', english: 'Finger', icon: '👆' },
  { latin: 'pectus', english: 'Chest', icon: '👕' },
  { latin: 'venter', english: 'Belly / stomach', icon: '⭕' },
  { latin: 'tergum', english: 'Back', icon: '🎒' },
  { latin: 'crus', english: 'Leg', icon: '🦵' },
  { latin: 'pes', english: 'Foot', icon: '🦶' },
  { latin: 'facies', english: 'Face', icon: '🙂' },
  { latin: 'frons', english: 'Forehead', icon: '🔝' },
  { latin: 'oculus', english: 'Eye', icon: '👁️' },
  { latin: 'cilium', english: 'Eyelash', icon: '✨' },
  { latin: 'nasus', english: 'Nose', icon: '👃' },
  { latin: 'aures', english: 'Ears', icon: '👂' },
  { latin: 'maxilla', english: 'Jaw', icon: '🦴' },
  { latin: 'dents', english: 'Tooth / teeth', icon: '🦷' },
  { latin: 'lingua', english: 'Tongue', icon: '👅' },
  { latin: 'cor', english: 'Heart', icon: '🫀' },
  { latin: 'pulmo', english: 'Lung', icon: '🫁' },
  { latin: 'hepar', english: 'Liver', icon: '🥩' },
  { latin: 'ren', english: 'Kidney', icon: '🫘' },
];

/** All rooms sub-lesson cards. */
export const ROOMS_ALL_FLASHCARDS: VocabularyFlashcard[] = [
  { latin: 'cubiculum', english: 'bedroom', icon: '🏠' },
  { latin: 'dormitorium', english: 'sleeping room / dormitory', icon: '🛌' },
  { latin: 'lectus', english: 'bed', icon: '🛏️' },
  { latin: 'culina', english: 'kitchen', icon: '🍳' },
  { latin: 'triclinium', english: 'dining room (Roman style)', icon: '🍽️' },
  { latin: 'atrium', english: 'main hall / central room', icon: '🔆' },
  { latin: 'tablinum', english: 'study / office (Roman house)', icon: '📜' },
  { latin: 'cella', english: 'small room / chamber', icon: '🚪' },
  { latin: 'camera', english: 'room / chamber', icon: '🏠' },
  { latin: 'balneum', english: 'bath / bathroom', icon: '🛁' },
  { latin: 'lavatorium', english: 'washing room', icon: '🧼' },
  { latin: 'bibliotheca', english: 'library', icon: '📚' },
  { latin: 'officina', english: 'workshop / workroom', icon: '🔧' },
  { latin: 'hortus', english: 'garden', icon: '🌳' },
  { latin: 'peristylium', english: 'courtyard with columns', icon: '🏛️' },
];
